[project]
name = "covariate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chelsa-cmip6>=1.4",
    "dask>=2026.3.0",
    "db-dtypes>=1.5.0",
    "google-cloud-bigquery>=3.40.1",
    "h5netcdf>=1.8.1",
    "h5py>=3.16.0",
    "netcdf4>=1.7.3",
    "pandas>=2.3.3",
    "rasterio>=1.4.4",
    "xarray>=2025.6.1",
    "zarr>=2.18.3",
]
